Using ProtoBuf instead of RLP in the rawdb
dominant-strategies/go-quai-libp2p pull request #100
Opened 2024-02-20 20:53 UTC by gameofpointers

2024-02-20 21:23 UTC, wizeguyy approved these changes

2024-02-20 21:57 UTC, jdowning100 commented on quai/backend.go
> -	if uncleanShutdowns, discards, err := rawdb.PushUncleanShutdownMarker(chainDb, logger); err != nil {
Is it not useful to know about unclean shutdowns?

2024-02-20 22:17 UTC, Djadih commented on core/bodydb.go
> -	block := rawdb.ReadBlock(bc.db, hash, number)
This works, but why did we not have to pass in location when using RLP?

2024-02-20 22:23 UTC, Djadih commented on core/types/proto_block.proto
> +}
Are all of these indeed optional?

2024-02-20 22:23 UTC, Djadih commented on core/types/receipt.go
> +func (rs ReceiptsForStorage) ProtoEncode() (*ProtoReceiptsForStorage, error) {
Function should be pointer receiver

2024-02-20 22:25 UTC, Djadih requested changes
Resolve conversations

2024-02-20 22:48 UTC, gameofpointers commented on core/types/proto_block.proto
> +}
optional enables the enforcement of these fields over the wire

2024-02-20 22:48 UTC, gameofpointers commented on core/types/receipt.go
> +func (rs ReceiptsForStorage) ProtoEncode() (*ProtoReceiptsForStorage, error) {
there is not reason for that in the encoding process and moreover the slice is a pointer in golang, it will reference correctly

2024-02-20 22:49 UTC, gameofpointers commented on core/bodydb.go
> -	block := rawdb.ReadBlock(bc.db, hash, number)
this is a requirement now, RLP was basically nor working

2024-02-20 22:52 UTC, gameofpointers commented on quai/backend.go
> -	if uncleanShutdowns, discards, err := rawdb.PushUncleanShutdownMarker(chainDb, logger); err != nil {
It is, i dont think this is being used the right way and it needs protobuf changes, so decided to remove it now and we can add it back, will create an issue to track this

2024-02-20 22:53 UTC, gameofpointers commented on quai/backend.go
> -	if uncleanShutdowns, discards, err := rawdb.PushUncleanShutdownMarker(chainDb, logger); err != nil {
https://github.com/dominant-strategies/go-quai/issues/1454

2024-02-20 22:54 UTC, Djadih commented on core/types/receipt.go
> +func (rs ReceiptsForStorage) ProtoEncode() (*ProtoReceiptsForStorage, error) {
I was just saying for consistency since the others are all pointer receivers. I agree it probably won't make a difference

2024-02-20 23:12 UTC, jdowning100 approved these changes

2024-02-21 16:15 UTC, Djadih approved these changes

2024-02-21 16:22 UTC, gameofpointers commented on core/types/receipt.go
> +func (rs ReceiptsForStorage) ProtoEncode() (*ProtoReceiptsForStorage, error) {
I looked at all the ProtoEncode methods, from what i can tell the difference in using pointer receivers is for the types that are used as pointers throughout the codebase, for example headers are pointers but some other data types like PendingEtxs where we don't, so its a broader question of using pointers in the codebase. So can we continue with this PR and come back to this question at a later point in time?

2024-02-21 16:24 UTC, merged