Calculate Reward stub and convert functions for Qi and Quai
dominant-strategies/go-quai-libp2p pull request #108
Opened 2024-02-23 17:57 UTC by kiltsonfire

2024-02-23 20:53 UTC, jdowning100 commented on consensus/misc/rewards.go
> +// CalculateQiReward caculates the qi that can be received for mining a block and returns value in its
Returns value in qits

2024-02-23 20:54 UTC, jdowning100 commented on consensus/misc/rewards.go
> +// CalculateQuaiReward calculates the quai that can be recieved for mining a block and returns value in qits
returns value in its

2024-02-23 20:57 UTC, jdowning100 commented on consensus/misc/rewards.go
> +	return common.Big1
Can I request that the stub returns more? For testing. Maybe max denomination

2024-02-26 21:45 UTC, Djadih submitted a review, later dismissed

2024-02-27 22:51 UTC, Djadih requested changes

2024-02-27 22:51 UTC, Djadih commented on consensus/misc/rewards.go
This file has merge conflicts to main

2024-02-27 23:50 UTC, merged