Import all go-quai flags and convert coinbase flags to json dictionary
dominant-strategies/go-quai-libp2p pull request #21
Opened 2023-12-14 16:21 UTC by robschleusner

2023-12-14 16:38 UTC, Djadih commented on cmd/utils/customflags.go
> +var DefaultCoinbaseMap = map[string]string{
This might be better for the end user and devs to have in a separate file called `coinbase.go`. It will be easier to find and modify.

2023-12-14 19:29 UTC, gameofpointers commented on cmd/utils/flags.go
> +	for i := 0; i < 16; i++ {
maybe make 16 a constant

2023-12-14 19:29 UTC, gameofpointers commented on cmd/utils/flags.go
> +		for j := 0; j < 16; j++ {
here as well

2023-12-19 14:33 UTC, robschleusner commented on cmd/utils/customflags.go
> +var DefaultCoinbaseMap = map[string]string{
Created coinbase.go still in utils package. 

Do we still want to have a coinbase.json where users can add their addresses if they want which will overwrite the coinbase.go defaults? Or do we just want users to adjust the coinbase.go file

2023-12-19 19:31 UTC, gameofpointers commented on cmd/utils/defaults.go
> +	Width           = 16          // Width of the network ontology
MaxWidth is probably a better name. @wizeguyy  what do you think?

2023-12-19 19:31 UTC, gameofpointers commented on cmd/utils/defaults.go
> +	Width           = 16          // Width of the network ontology
Instead of defining all at once, it should loop through what is defined

2023-12-19 20:57 UTC, wizeguyy commented on cmd/utils/defaults.go
> +	Width           = 16          // Width of the network ontology
agreed

2023-12-19 21:00 UTC, wizeguyy requested changes

2023-12-19 21:00 UTC, wizeguyy commented on coinbases.json
please do not create config files in the repo directory. Configs are stored in the XDG compliant config data directory (see how we load configurations elsewhere).

2023-12-19 21:02 UTC, wizeguyy commented
@robschleusner I expect two ways to specify coinbases to go-quai:
1) provide list of coinbases supplied as CLI argument
2) coinbases read from file in config dir

Can you confirm that is the case, and give an example of the command you run?

2023-12-20 15:27 UTC, robschleusner commented
> @robschleusner I expect two ways to specify coinbases to go-quai:
> 
> 1. provide list of coinbases supplied as CLI argument
> 2. coinbases read from  the config.toml (either in the XDG config dir or a user defined location)
> 
> Can you confirm that is the case, and give an example of the command you run?

@wizeguyy 

Do you need the coinbases to be stored in the same config.toml as XDG? The default XDG config directory is tucked away in the system files. For a user to change the coinbase address input, they'd have to find that directory, find the coinbaseAddresses within the directory and make the changes. It also means that the config.toml will have at least 256 additional lines.

Additionally, right now I have it so that the same flag takes either file path input (example 2 below) or coinbase address input (example 1 below). Adding the coinbases to a config with other options in it would further complicate the cli input for the user because the address input (example 1) would have to match toml structure.

When you say either in XDG location or user defined location, do you mean that the user would define a new XDG location through --config-dir and the coinbases would be read from there? 

I have updated the parsing to receive toml instead of json, and here are the two ways to input.

1. `go run main.go start --coinbase "'01'='0x01a1f109551bd432803012645ac136ddd64dba72'"`
2. (Default) Coinbases read from path. --coinbase ./config/coinbases.toml. The XDG config dir is located in a different location than the project and not read from at the moment.

2023-12-20 15:58 UTC, wizeguyy commented
@robschleusner yes, I expect the user's coinbase addresses to be a section in the config.toml file, wherever the user chooses to locate that file. Today, the default location is in the XDG config directory (the standard place to keep config files), but the user is welcome to specify another location for the config file as a CLI argument.

Note, the user doesn't have to put their coinbase addresses into the config file. They may omit that section, and then the CLI arg parser should require that they provide addresses as a CLI argument to enable mining.

What I don't want:
1) separate coinbases file. coinbase addresses should just be a section in the config.toml
1) any config file or user data file in the repository. The repository is only for things relating to _building_ the binary (code, docs, toolchain, etc) and NOT for things related to _using_ the binary.

2023-12-20 16:54 UTC, robschleusner commented
Just to confirm - the only thing that the coinbase flag would be used for would be to pass in specific addresses through the CLI. Do you have a specific format you would want? JSON string (`--coinbase '{"00":"address0","01":"address1"}'`)? 

If there is no coinbase flag specified, the node will check the config.toml. 

If there is nothing in the config.toml, it reverts to the defaults specified in the utils/defaultcoinbases.go file

2023-12-20 18:35 UTC, wizeguyy commented
> Just to confirm - the only thing that the coinbase flag would be used for would be to pass in specific addresses through the CLI.

correct

> Do you have a specific format you would want?

JSON

> If there is no coinbase flag specified, the node will check the config.toml.

The exact workflow is a bit different:
1) viper/cobra initializes all arguments to default values (coinbases should default to empty map)
1) then it reads the TOML and loads in any values provided there, overriding the defaults
1) then it parses the CLI args, and any args found in the CLI, it override what was found in the TOML/default

> f there is nothing in the config.toml, it reverts to the defaults specified in the utils/defaultcoinbases.go file. Or should it throw an error.

No, there will be no default coinbase addresses. It should throw an error _iff_ they attempt to start mining (i.e. build pending headers) for a shard that doesn't have a coinbase specified.

2024-01-05 18:28 UTC, closed without merging