Add UTXO Set for Qi
dominant-strategies/go-quai-libp2p pull request #46
Opened 2024-01-19 18:38 UTC by jdowning100

This PR adds a UTXO set to the protocol as defined in [QIP 7](https://github.com/quai-network/qips/blob/master/qip-0007.md). The value of the UTXO can be one of 16 denominations. This is a draft PR for your reference and is not intended to be merged into go-quai-libp2p, rather it should be merged into the main go-quai repo. Please review and add comments for things that should be fixed. Peering is untested.

2024-01-20 03:10 UTC, alanorwick requested changes

2024-01-20 03:10 UTC, alanorwick commented on consensus/misc/rewards.go
> +func CalculateRewardForQiWithFees(header *types.Header, fees *big.Int) map[uint8]uint8 {
The reward in this branch for local is not large enough. Need to make the denominations smaller or increase the reward from `10e8` to `10e9`.

2024-01-21 21:04 UTC, jdowning100 commented on consensus/misc/rewards.go
> +func CalculateRewardForQiWithFees(header *types.Header, fees *big.Int) map[uint8]uint8 {
This PR follows the QIP 7 spec with regards to the denominations. If you would like to make a PR to increase the reward in the the case of local, I'd be open to that, but make the PR against go-quai main. I tried doing that previously here: https://github.com/dominant-strategies/go-quai/pull/1214

2024-02-21 23:10 UTC, jdowning100 commented
Closed in favor of https://github.com/dominant-strategies/go-quai-libp2p/pull/82

2024-02-21 23:10 UTC, closed without merging