UTXO work
dominant-strategies/go-quai-libp2p pull request #82
Opened 2024-02-08 23:04 UTC by alanorwick

2024-02-09 19:11 UTC, jdowning100 commented on core/rawdb/accessors_chain.go
> +		return nil
Should log an error here

2024-02-09 19:23 UTC, jdowning100 commented on quaiclient/ethclient/ethclient.go
> +	// TODO: Fix the checking here on manifest hashes in RPC
@gameofpointers should we keep this commented out?

2024-02-09 19:28 UTC, jdowning100 commented on core/headerchain.go
> +					if utxo.Denomination == entry.Denomination &&
Because there can be two UTXOs created for the same address in the same denomination in the same block, we need to make sure t hat the address utxos table is NOT used for consensus in any way, only for information for a user.

2024-02-09 19:31 UTC, jdowning100 commented on core/headerchain.go
> +	addressUtxoPrefix := []byte("au")
All of the db prefixes are in schema.go, I recommend moving it there

2024-02-09 19:34 UTC, jdowning100 commented on core/headerchain.go
> +	for it.Next() {
You iterate over every address in the index on node startup. Why? It could take a while and doesn't seem necessary.

2024-02-09 19:35 UTC, jdowning100 commented on core/headerchain.go
> +		end[len(end)-1]++
Need comments explaining this logic

2024-02-09 19:46 UTC, jdowning100 commented on core/types/stxo_validate.go
> +	for _, tx := range block.UTXOs()[1:] { // need to make sure this is correct
Remove this comment; it's correct

2024-02-09 19:48 UTC, jdowning100 commented on internal/quaiapi/api.go
> +	return (*hexutil.Big)(balance), nil
If balance is nil I'm pretty sure this will crash the node

2024-02-09 19:56 UTC, jdowning100 commented on core/worker.go
> +		if tx.Type() != types.UtxoTxType {
Strange to put this in the encoding/decoding commit, this should be in a prior commit (nitpick)

2024-02-09 19:59 UTC, jdowning100 commented
The logic for EVM state coinbase transaction isn't done and neither is the logic to have the miner choose which coinbase he wants. This means that every block has two coinbases. I will work on fixing this.

2024-02-09 20:45 UTC, alanorwick commented on core/headerchain.go
> +	addressUtxoPrefix := []byte("au")
we would then need to export it `addressUtxoPrefix` -> `AddressUtxoPrefix`

2024-02-09 20:45 UTC, alanorwick commented on core/headerchain.go
> +	addressUtxoPrefix := []byte("au")
can also move the method there

2024-02-09 20:45 UTC, alanorwick commented on core/headerchain.go
> +	for it.Next() {
We could break if it's >1 I suppose

2024-02-09 20:46 UTC, alanorwick commented on core/headerchain.go
> +		end[len(end)-1]++
Will add

2024-02-09 20:46 UTC, alanorwick commented on core/types/stxo_validate.go
> +	for _, tx := range block.UTXOs()[1:] { // need to make sure this is correct
will do

2024-02-09 20:46 UTC, alanorwick commented on internal/quaiapi/api.go
> +	return (*hexutil.Big)(balance), nil
so we need to add a check?

2024-02-09 20:46 UTC, alanorwick commented on core/worker.go
> +		if tx.Type() != types.UtxoTxType {
correct, likely from my best attempt at fixing the git history

2024-02-09 20:59 UTC, jdowning100 commented on core/headerchain.go
> +	for it.Next() {
Or don't iterate over all the addresses if hc.indexerConfig.IndexAddressUtxos is set to true. If it's false, it should usually be empty except for the first time.

2024-02-09 21:00 UTC, jdowning100 commented on core/headerchain.go
> +	addressUtxoPrefix := []byte("au")
Exporting is fine.

2024-02-09 21:06 UTC, jdowning100 commented on internal/quaiapi/api.go
> +	return (*hexutil.Big)(balance), nil
Yes

2024-02-09 21:45 UTC, jdowning100 commented on core/types/stxo_validate.go
> -	for _, tx := range block.UTXOs()[1:] { // need to make sure this is correct
Please squash this

2024-02-09 22:47 UTC, alanorwick commented on core/headerchain.go
> +					if utxo.Denomination == entry.Denomination &&
yeah only for user info. it's not part of the header / processing

2024-02-12 19:56 UTC, wizeguyy commented on core/rawdb/accessors_chain.go
> +func WriteSpentUTXOs(db ethdb.KeyValueWriter, hash common.Hash, spentUTXOs *[]types.SpentTxOut) {
Why are we writing spent UTXOs? If there is ever a need to reference an old UTXO, it should probably be done by looking up the block->tx->txo.

2024-02-12 19:57 UTC, wizeguyy commented on core/types/block.go
> +func (b *Block) UTXOs() []*Transaction {
This method should be renamed `UtxoTransactions()`

2024-02-12 20:01 UTC, wizeguyy commented on core/types/block.go
> +func (b *Block) UTXOs() []*Transaction {
Actually, if #2 is true, then rather than having two filter methods, it would be more performant to have one filter that returns two lists

2024-02-12 20:03 UTC, wizeguyy commented on core/types/stxo_validate.go
> +func CountSpentOutputs(block *Block) int {
Why is this needed? Seems like it isn't used anywhere

2024-02-12 20:06 UTC, wizeguyy commented on core/types/transaction.go
> +	// do we need a tx version?
Ethereum has not had TX versions. When they add new transactions, they add new transaction types. We have been following  this convention, so no need for tx versions today

2024-02-12 20:15 UTC, wizeguyy commented on core/types/utxo_tx.go
> +	ChainID *big.Int // replay protection
replay protection is afforded to us in the signer. No need for it here.

2024-02-12 20:17 UTC, jdowning100 commented on core/rawdb/accessors_chain.go
> +func WriteSpentUTXOs(db ethdb.KeyValueWriter, hash common.Hash, spentUTXOs *[]types.SpentTxOut) {
We look up the spent txo to unspend them in the event of a re-org

2024-02-12 20:18 UTC, wizeguyy commented on core/types/utxo_tx.go
> +	if tx.ChainID != nil {
We should not guard situations like this.

It should be illegal to have a UTXO tx with no chain ID. If this ever happens, something is hopelessly wrong, and the node should halt and catch fire.

2024-02-12 20:18 UTC, jdowning100 commented on core/rawdb/accessors_chain.go
> +func WriteSpentUTXOs(db ethdb.KeyValueWriter, hash common.Hash, spentUTXOs *[]types.SpentTxOut) {
This is from BTCD. We may not actually need it because we can infer the UTXOs with the inputs in the block

2024-02-12 20:25 UTC, jdowning100 commented on core/types/block.go
> +func (b *Block) UTXOs() []*Transaction {
I don't think we need to return two lists if only one is ever used at a time. We could add a QuaiTransactions() method, but I'm not sure that it would be used

2024-02-12 20:28 UTC, wizeguyy commented on core/types/utxo_tx.go
> +}
Where does the signature go?

2024-02-12 20:31 UTC, wizeguyy commented on core/types/utxo_validate.go
> +func IsCoinBaseTx(msgTx *Transaction) bool {
Coinbase tx hashes will not be unique

2024-02-12 20:31 UTC, jdowning100 commented on core/types/stxo_validate.go
> +func CountSpentOutputs(block *Block) int {
It is used in three locations

2024-02-12 20:33 UTC, jdowning100 commented on core/types/block.go
> +func (b *Block) UTXOs() []*Transaction {
Perhaps we should rename utxo_tx to Qi_tx

2024-02-12 20:33 UTC, jdowning100 commented on core/types/utxo_tx.go
> +}
It's in the Tx *Transaction

2024-02-12 20:35 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	if tx.ChainID != nil {
https://github.com/dominant-strategies/go-quai-libp2p/blob/main/core/types/internal_tx.go#L63
I agree, but we should make this change in all copy functions for consistency

2024-02-12 20:35 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
@alanorwick change to "UTXO TX does not have ECDSA signature values"

2024-02-12 20:40 UTC, jdowning100 commented on core/types/utxo_validate.go
> +func IsCoinBaseTx(msgTx *Transaction) bool {
That is correct. Can you explain what you're referencing here?

2024-02-12 20:47 UTC, jdowning100 commented on core/rawdb/accessors_chain.go
> +func WriteSpentUTXOs(db ethdb.KeyValueWriter, hash common.Hash, spentUTXOs *[]types.SpentTxOut) {
Also, this data can be pruned easily. It's very unlikely that we need this data past 1k blocks

2024-02-12 23:14 UTC, alanorwick commented on core/types/stxo_validate.go
> +type SpentTxOut struct {
Agreed with @jdowning100

2024-02-12 23:14 UTC, alanorwick commented on core/types/stxo_validate.go
> +func CountSpentOutputs(block *Block) int {
Agreed with @jdowning100

2024-02-12 23:14 UTC, alanorwick commented on core/types/block.go
> +func (b *Block) UTXOs() []*Transaction {
Renaming to `QiTransactions` feels appropriate

2024-02-12 23:15 UTC, alanorwick commented on core/rawdb/accessors_chain.go
> +func WriteSpentUTXOs(db ethdb.KeyValueWriter, hash common.Hash, spentUTXOs *[]types.SpentTxOut) {
Agreed with @jdowning100

2024-02-12 23:15 UTC, alanorwick commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
@jdowning100 can do

2024-02-13 15:48 UTC, alanorwick commented on core/types/transaction.go
> +	// do we need a tx version?
removed the comment

2024-02-13 17:35 UTC, wizeguyy commented on core/types/stxo_validate.go
> +func CountSpentOutputs(block *Block) int {
oh, I guess I haven't got to the commit where it is used. Probably went into the wrong commit then. No worries.

2024-02-13 17:36 UTC, wizeguyy commented on core/types/stxo_validate.go
> +type SpentTxOut struct {
same comment as above

2024-02-13 17:37 UTC, wizeguyy commented on core/types/utxo_tx.go
> +	if tx.ChainID != nil {
I agree. Feel free to create an issue to do it later if you'd rather.

2024-02-13 17:38 UTC, wizeguyy commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
What about MuSig signature values? The method should be renamed, because UTXO transactions will definitely have signature values.

2024-02-13 17:49 UTC, wizeguyy commented on core/types/utxo_validate.go
> +func IsCoinBaseTx(msgTx *Transaction) bool {
How will someone be able to look up a coinbase TX by hash, e.g. via the RPC?

Transaction hashes need to be unique. We talked about a handful of techniques to guarantee this, but I don't remember which we landed on. These are the options I can remember:
1) coinbase tx input prevout = parent block hash
2) coinbase tx input pubkey = parent block hash

2024-02-13 17:49 UTC, wizeguyy commented on core/types/utxo_validate.go
> +func IsCoinBaseTx(msgTx *Transaction) bool {
tbf, this should be defined in QIP-0007, whatever we decide. Thoughts?

2024-02-13 18:20 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
Signature values in this context refers to the v,r,s ECDSA signature values. We have a separate function for the schnorr signature (called utxoSignature)

2024-02-13 18:21 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
We must have two separate functions for signatures because they return two different signature types

2024-02-13 18:22 UTC, jdowning100 commented on core/types/utxo_validate.go
> +func IsCoinBaseTx(msgTx *Transaction) bool {
Coinbase tx input prev output hash = parent block hash

2024-02-13 18:23 UTC, wizeguyy commented on core/types/stxo_validate.go
> +	IsCoinBase bool
I'm skeptical that this field should exist.

you say `SpentTxOut` is only used when writing the spent TXO list for every block that gets processed. Then wouldn't that mean the first TX in that list is always the coinbase TX?

2024-02-13 18:26 UTC, wizeguyy commented on core/types/utxo_validate.go
> +// requirements are met, detecting double spends, validating all values and fees
> ensuring the coinbase seasoning requirements are met

Where is this done?

2024-02-13 18:26 UTC, wizeguyy commented on core/types/utxo_validate.go
> +	var totalSatoshiIn uint64
Why are we calling these Satoshis?

2024-02-13 18:26 UTC, alanorwick commented on core/types/transaction.go
> +	// do we need a tx version?
apologies, check now

2024-02-13 18:27 UTC, wizeguyy commented on core/types/utxo.go
> +	Value   uint64
Value should be an 8 bit denomination

2024-02-13 18:27 UTC, alanorwick commented on core/types/utxo_validate.go
> +	var totalSatoshiIn uint64
good catch, will update

2024-02-13 18:27 UTC, wizeguyy commented on core/types/utxo_validate.go
> +		totalSatoshiOut += txOut.Value
tx denomination needs to be converted to value before summing

2024-02-13 18:28 UTC, wizeguyy commented on core/types/utxo_validate.go
> +		// Check transaction inputs
This should definitely happen

2024-02-13 18:30 UTC, alanorwick commented on core/types/utxo_validate.go
> +	var totalSatoshiIn uint64
renamed to Qi

2024-02-13 18:31 UTC, alanorwick commented on core/types/utxo.go
> +	Value   uint64
also says bitcoin here 😵‍💫 will fix

2024-02-13 18:32 UTC, alanorwick commented on core/types/utxo.go
> +	Value   uint64
this is updated

2024-02-13 18:57 UTC, alanorwick commented on core/types/utxo_validate.go
> +// requirements are met, detecting double spends, validating all values and fees
That is not done / applicable. It is an old comment.

2024-02-13 18:58 UTC, alanorwick commented on core/types/utxo_validate.go
> +// requirements are met, detecting double spends, validating all values and fees
Although we are deciding the age in of Quai / coinbase. Opened an issue https://github.com/dominant-strategies/go-quai/issues/1444

2024-02-13 19:34 UTC, wizeguyy commented on core/types/utxo_viewpoint.go
> +	Amount      uint64
again, amount needs to be denomination, not u64

2024-02-13 19:35 UTC, wizeguyy commented on core/types/utxo_viewpoint.go
> +func (entry *UtxoEntry) IsModified() bool {
Why would we modify a UTXO entry?

2024-02-13 19:37 UTC, wizeguyy commented on core/types/utxo_viewpoint.go
> +func (entry *UtxoEntry) IsSpent() bool {
Why would we have a UtxoEntry if it is spent? Then it is no longer a UTXO. Then it becomes a TXO. _and_ we don't keep it around in the set, so why bother indicating it?

2024-02-13 19:39 UTC, wizeguyy commented on core/types/utxo_viewpoint.go
> +	bestHash common.Hash
Can you please ELI5 `bestHash`? How can a viewpoint be valid for more than one block?

2024-02-13 19:42 UTC, wizeguyy commented on core/types/utxo.go
> +	Hash  common.Hash
Prefer to call this TxHash so it does not get confused with BlockHashes or something else.

2024-02-13 19:42 UTC, wizeguyy commented on core/types/utxo_viewpoint.go
> +	entry.PackedFlags |= TfSpent | TfModified
Why not just remove the entry after it is spent?

2024-02-13 19:43 UTC, wizeguyy commented on core/types/utxo_viewpoint.go
> +// NOTE: This is an implementation of the txscript.PrevOutputFetcher interface.
I can't find this interface. Where is it?

2024-02-13 19:47 UTC, wizeguyy commented on core/headerchain.go
> +// SetCurrentState updates the current state and UTXO set upon which the current pending block is built
> updates the current state and UTXO set

(nit) UTXO set is part of the current state

2024-02-13 19:50 UTC, wizeguyy commented on core/headerchain.go
> +			if types.IsCoinBaseTx(tx) && !coinbase {
only the very first tx is allowed to be coinbase. Doesn't make sense to do this check in the loop

2024-02-13 19:52 UTC, wizeguyy commented on core/types/utxo.go
> +	Value   uint64
what do you mean? I still see a u64 when I refresh

2024-02-13 19:53 UTC, wizeguyy commented on core/types/stxo_validate.go
Why is this file called `stxo_validate.go`? It doesn't appear to have any validation logic for anything

2024-02-13 20:01 UTC, wizeguyy commented on core/headerchain.go
> +		}
Where does the transaction signature get validated?

2024-02-13 20:02 UTC, wizeguyy commented on core/headerchain.go
> +			_, err = types.CheckTransactionInputs(tx, block.Header().NumberU64(nodeCtx), utxoView)
What does `CheckTransactionInputs()` that isn't covered by `verifyInputUtxos()`?

2024-02-13 20:04 UTC, wizeguyy commented on core/headerchain.go
> +			return ErrSubNotSyncedToDom
I don't think this condition is an indication that the sub is not synced to the dom. The block could just be disconnected.

2024-02-13 20:06 UTC, wizeguyy commented on core/headerchain.go
> +		err = hc.verifyInputUtxos(utxoView, block, hc.pool.signer)
Haven't all of these blocks already been verified?

2024-02-13 20:24 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +	bestHash common.Hash
It's unused and should be removed

2024-02-13 20:24 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +// NOTE: This is an implementation of the txscript.PrevOutputFetcher interface.
This function is unused and should be removed.

2024-02-13 20:25 UTC, jdowning100 commented on core/headerchain.go
> +// SetCurrentState updates the current state and UTXO set upon which the current pending block is built
True, comment should read "SetCurrentState updates the current Quai state and Qi UTXO set upon which the current pending block is built"

2024-02-13 20:26 UTC, wizeguyy commented on core/types/utxo_validate.go
> +	var totalSatoshiIn uint64
but its not Qi either. Qi is some multiple of the base unit... what is our base unit?

2024-02-13 20:27 UTC, wizeguyy commented on core/types/utxo.go
> +	Denominations[0] = big.NewInt(5000000000000000)                                    // 0.005 Qi
Why is `0.005` == `5000000000000000`?

2024-02-13 20:29 UTC, wizeguyy commented on consensus/misc/rewards.go
> +	return new(big.Int).Mul(header.Difficulty(), big.NewInt(10e10))
why?

2024-02-13 20:30 UTC, wizeguyy commented on core/headerchain.go
> +			return fmt.Errorf("utxo not found")
How does this relate to RPC encoding?

2024-02-13 20:36 UTC, jdowning100 commented on core/headerchain.go
> +			_, err = types.CheckTransactionInputs(tx, block.Header().NumberU64(nodeCtx), utxoView)
CheckTransactionInputs returns the fees for the transaction, which is necessary to know how much to pay the miner. I could move the functionality to verifyInputUtxos() and return an aggregate fee, if that works better.

2024-02-13 20:36 UTC, jdowning100 commented on core/headerchain.go
> +		}
verifyInputUtxos()

2024-02-13 20:41 UTC, jdowning100 commented on core/headerchain.go
> +		err = hc.verifyInputUtxos(utxoView, block, hc.pool.signer)
I don't think that's guaranteed. A lower difficulty fork's blocks would get stored to disk, but the append process would only happen when the entropy reduction is greater than the current chain I'm mining on, and I would then switch to that chain, but I still have to do the verification and processing when I make the switch.

2024-02-13 20:50 UTC, jdowning100 commented on core/types/stxo_validate.go
> +	IsCoinBase bool
A coinbase transaction may have many outputs. The first n outpouts in the spent TXO list would correspond to the coinbase tx, but n could be any number (we should probably cap the size of the coinbase tx, though)

2024-02-13 20:53 UTC, jdowning100 commented on core/types/utxo_validate.go
> +		// Check transaction inputs
I believe the implementation is in the commit that adds denominations

2024-02-13 20:53 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +func (entry *UtxoEntry) IsSpent() bool {
We keep it around temporarily in the intermediate set, called a Viewpoint, which is later committed to the database (and all Spent UTXOs are removed from the db)

2024-02-13 20:54 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +	entry.PackedFlags |= TfSpent | TfModified
The entry is removed from the db after the viewpoint is committed to the database

2024-02-13 20:54 UTC, jdowning100 commented on core/types/stxo_validate.go
Agreed, file name should be changed

2024-02-13 21:09 UTC, jdowning100 commented on core/headerchain.go
> +			if types.IsCoinBaseTx(tx) && !coinbase {
True, at this point in the logic we've checked to make sure every tx except for the coinbase has valid inputs. So this is a duplicate check.

2024-02-13 21:10 UTC, jdowning100 commented on consensus/misc/rewards.go
> +	return new(big.Int).Mul(header.Difficulty(), big.NewInt(10e10))
@alanorwick did this to increase rewards for local (blake3). This should not be in the PR.

2024-02-13 21:11 UTC, jdowning100 commented on consensus/misc/rewards.go
> +	return new(big.Int).Mul(header.Difficulty(), big.NewInt(10e10))
However, I do think we should increase the rewards for blake3 (local) by an order of magnitude, in another PR.

2024-02-13 21:13 UTC, jdowning100 commented on core/headerchain.go
> +			return fmt.Errorf("utxo not found")
It does not relate to RPC encoding. This error is returned if a UTXO is not found (already spent or does not exist)

2024-02-13 21:16 UTC, wizeguyy commented on core/headerchain.go
> +	commonHeader := hc.findCommonStateHeadAncestor(head)
Please do not duplicate the reorg logic. Just add the UTXO state apply/revert operations into the existing reorg logic

2024-02-13 21:19 UTC, wizeguyy commented on core/headerchain.go
> +			return fmt.Errorf("utxo not found")
Then this is in the wrong commit

2024-02-13 21:23 UTC, jdowning100 commented on core/types/utxo.go
> +	Denominations[0] = big.NewInt(5000000000000000)                                    // 0.005 Qi
For example, if I were to subtract 99999.995 from 100000.005 with float64, the result is not actually 0.01 but a fractional number close to it

2024-02-13 21:30 UTC, wizeguyy requested changes
1) please do not use the ViewPoint data structure.
Its entire purpose is to ensure that UTXOs are removed from the set atomically at the end of block processing. We already have that guarantee by using the database batch write/commit operations. In-fact, if the viewpoint and batch-commit atomicity ever disagree, we have big trouble. This actually negates the benefits of our current batch write design.

1) please reorganize the PR. I should be able to review a commit by itself without knowing that "XYZ gets undone 2 commits later"

2024-02-13 22:52 UTC, jdowning100 commented on core/types/utxo_validate.go
> +	var totalSatoshiIn uint64
I believe @mechanikalk decided on "IT"

2024-02-13 22:53 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +// NOTE: This is an implementation of the txscript.PrevOutputFetcher interface.
Removed

2024-02-13 22:54 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +	bestHash common.Hash
Removed

2024-02-13 22:54 UTC, jdowning100 commented on core/types/utxo.go
> +	Hash  common.Hash
Changed

2024-02-13 23:30 UTC, jdowning100 commented on core/headerchain.go
> +			if types.IsCoinBaseTx(tx) && !coinbase {
Actually, it's not guaranteed that the first tx is a coinbase, so we still have to check for that. Updated

2024-02-14 05:08 UTC, jdowning100 commented on core/headerchain.go
> +			_, err = types.CheckTransactionInputs(tx, block.Header().NumberU64(nodeCtx), utxoView)
Fixed

2024-02-14 05:09 UTC, jdowning100 commented on core/headerchain.go
> +			if types.IsCoinBaseTx(tx) && !coinbase {
Fixed

2024-02-14 05:09 UTC, jdowning100 commented on core/headerchain.go
> +// SetCurrentState updates the current state and UTXO set upon which the current pending block is built
Fixed

2024-02-14 15:22 UTC, wizeguyy commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
Ok, lets name the functions accordingly then. Maybe `getSchnorrSig()` and `getEcdsaSig()`?

2024-02-14 16:28 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
That is fine with me

2024-02-15 18:41 UTC, jdowning100 commented on core/types/block.go
> +func (b *Block) UTXOs() []*Transaction {
I renamed UtxoTx to QiTx

2024-02-15 18:44 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	if tx.ChainID != nil {
https://github.com/dominant-strategies/go-quai/issues/1448

2024-02-15 18:45 UTC, jdowning100 commented on core/types/utxo_tx.go
> +	panic("UTXO TX does not have signature values")
Renamed to getEdsaSignatureValues() setEcdsaSignatureValues() and getSchnorrSignature()

2024-02-15 18:45 UTC, jdowning100 commented on core/types/utxo_validate.go
> +func IsCoinBaseTx(msgTx *Transaction) bool {
Fixed

2024-02-15 18:46 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +	Amount      uint64
Denominations added in a later commit

2024-02-15 20:20 UTC, wizeguyy commented on consensus/misc/rewards.go
> +	return new(big.Int).Mul(header.Difficulty(), big.NewInt(10e10))
so we're removing this, right?

2024-02-15 20:24 UTC, wizeguyy commented on quaiclient/ethclient/ethclient.go
> +	// TODO: Fix the checking here on manifest hashes in RPC
lets delete this or uncomment it.

2024-02-15 20:29 UTC, wizeguyy commented on core/types/utxo_validate.go
> +	totalQiIn := big.NewInt(0)
we can't call these Qi. These are units of 0.0005 Qi or something

2024-02-15 20:38 UTC, wizeguyy commented on core/types/utxo.go
> +	Denominations[0] = big.NewInt(5000000000000000)                                    // 0.005 Qi
but values should not be floating point numbers. A u64 is sufficient. Then you don't need to worry about precision.

2024-02-15 21:33 UTC, jdowning100 commented on core/types/utxo_validate.go
> +	totalQiIn := big.NewInt(0)
Changed to Qit

2024-02-15 21:34 UTC, jdowning100 commented on quaiclient/ethclient/ethclient.go
> +	// TODO: Fix the checking here on manifest hashes in RPC
Removed

2024-02-15 21:34 UTC, jdowning100 commented on core/types/utxo_validate.go
> +	var totalSatoshiIn uint64
Changed to Qit

2024-02-15 21:34 UTC, jdowning100 commented on core/types/stxo_validate.go
Changed

2024-02-17 16:20 UTC, jdowning100 commented on core/types/utxo.go
> +	Denominations[0] = big.NewInt(5000000000000000)                                    // 0.005 Qi
Fixed

2024-02-20 22:14 UTC, wizeguyy submitted a review, later dismissed

2024-02-21 16:08 UTC, wizeguyy approved these changes

2024-02-21 17:21 UTC, wizeguyy approved these changes

2024-02-21 19:17 UTC, gameofpointers commented on core/headerchain.go
> +			address := common.BytesToAddress(crypto.Keccak256(txIn.PubKey[1:])[12:], hc.NodeLocation())
we should make this a function because it would be hard to track it in the future, a pubkey to address function

2024-02-21 19:17 UTC, gameofpointers commented on core/headerchain.go
> +		if len(tx.TxIn()) > 1 {
we should probably use the same aggregateKeys method to get the finalKey

2024-02-21 19:17 UTC, gameofpointers commented on core/headerchain.go
> +func createCoinbaseTx(header *types.Header) (*types.Transaction, error) {
@jdowning100 said its not used, so we can delete it

2024-02-21 19:17 UTC, gameofpointers commented on core/state_processor.go
> +	for i, tx := range block.Transactions()[1:] {
why are we not going through the transactions

2024-02-21 19:24 UTC, gameofpointers commented on core/types/stxo.go
> +	for _, tx := range block.QiTransactions()[1:] { // need to make sure this is correct
dont we need to go thorugh all the transactions? since the first one is not neccessarily a coinbase ?

2024-02-21 19:24 UTC, gameofpointers commented on core/types/transaction.go
> +		if protoTx.To == nil {
cant check To for the type 1, there was a PR that made the change, need to pull those changes back in 9a6fa6b6

2024-02-21 19:27 UTC, gameofpointers commented on core/types/utxo_viewpoint.go
> +	if len(tx.TxIn()) > 1 {
probably use the same library to get the finalKey

2024-02-21 21:08 UTC, jdowning100 commented on core/types/utxo_viewpoint.go
> +	if len(tx.TxIn()) > 1 {
Is this a duplicate of your previous comment?

2024-02-21 21:09 UTC, jdowning100 commented on core/headerchain.go
> +	newBlock := hc.GetBlockOrCandidateByHash(head.Hash())
Fixed

2024-02-21 21:09 UTC, jdowning100 commented on core/headerchain.go
> +		newBlock = hc.GetBlockOrCandidate(newBlock.ParentHash(nodeCtx), newBlock.NumberU64(nodeCtx)-1)
Fixed

2024-02-21 21:09 UTC, jdowning100 commented on core/headerchain.go
> +	for i, tx := range transactions[1:] {
Fixed

2024-02-21 21:09 UTC, jdowning100 commented on core/headerchain.go
> +			address := common.BytesToAddress(crypto.Keccak256(txIn.PubKey[1:])[12:], hc.NodeLocation())
Fixed

2024-02-21 21:10 UTC, jdowning100 commented on core/types/stxo.go
> +	for _, tx := range block.QiTransactions()[1:] { // need to make sure this is correct
Fixed

2024-02-21 21:23 UTC, jdowning100 commented on core/headerchain.go
> +	for i := 15; i >= 0; i-- {
Fixed

2024-02-21 21:30 UTC, jdowning100 commented on core/types/transaction.go
> +		if protoTx.To == nil {
Fixed

2024-02-21 21:34 UTC, jdowning100 commented on core/state_processor.go
> +	for i, tx := range block.Transactions()[1:] {
Fixed

2024-02-21 22:52 UTC, gameofpointers approved these changes

2024-02-21 23:03 UTC, jdowning100 approved these changes

2024-02-21 23:07 UTC, merged